### PR TITLE
Expand projects in document search results

### LINKED ISSUE #790: Helpful metadata is missing from document list items
[Feedback](https://baserow.io/database/128523/table/332915/575722/row/232):

> I really miss the project and tag/keyval listed with the files. even if just file belongs to a project or not would be useful information. I like how it is faster and more slicker, Thank you!

Screenshot 2024-10-25 at 10 01 29 AM

We've got lots of whitespace on the right side and the last line list items to restore a display of   metadata. We can prioritize Projects and Tags, with a limit of 5 items and an indicator if there's more to show.

### PR DESCRIPTION
**Pull request by allanlasser**
Closes #790

We already have the capability to display projects on document search results, but we weren't expanding them in the API request.

### CODE REVIEW

**Comment by allanlasser** [comment]
Screenshot 2024-10-28 at 3 56 27 PM

This needs some additional wrapping and overflow handling

**Comment by eyeseast** [comment]
Something weird happening at mobile width:

Screenshot 2024-10-30 at 9 28 22 AM

**Comment by allanlasser** [comment]
> Something weird happening at mobile width

That is intentional styling for mobile, and clearly it needs some work!

**Comment by eyeseast** [comment]
Just noticed that I'm also seeing some overflow on the list view:

Screenshot 2024-10-30 at 10 16 28 AM

**Review by eyeseast — APPROVED** [review]

**Pull request merged**
