### PR TITLE
Switch to ES Module format

### LINKED ISSUE #327: Convert to module format
Right now, everything under `src/` uses ES modules with `import` statements, but our build and test configurations use CommonJS and `require`. That's starting to cause problems with our tooling. Modules are the future, so let's go all in.

- [ ] add `"type": "module"` to `package.json`
- [ ] convert Webpack configs to ES modules
- [ ] convert Jest config to ES module

### PR DESCRIPTION
**Pull request by eyeseast**
This makes the frontend run explicitly in module mode. See the differences here: https://nodejs.org/docs/latest-v18.x/api/packages.html#determining-module-system

Users shouldn't see any change with this.

Closes #327

### CODE REVIEW

**Comment by duckduckgrayduck** [comment]
Not sure if related, but in the preview when I try to add documents to a project it gives me issues with CSRF tokens: 
CSRF

**Review by allanlasser — COMMENTED** [review]
Code changes look fine to me. Haven't had any issues with running Webpack locally. The only issue I ran into on the preview deployment was a CSRF error when creating a new project, but that could be an existing bug.

**Comment by eyeseast** [comment]
CSRF issues should be fixed. It was an Axios update that broke cross-domain requests. I pinned the version for now. Please check again @duckduckgrayduck or @allanlasser.

**Comment by duckduckgrayduck** [comment]
Seems to be fixed for me @eyeseast

**Review by duckduckgrayduck — APPROVED** [review]

**Review by allanlasser — APPROVED** [review]
LGTM

**Pull request merged**
